# Developer profile
netgrif.engine.logging.endpoints=true

# MongoDB
netgrif.engine.data.database-name=${NETGRIF_ENGINE_DATA_DATABASE_NAME:nae}_dev
netgrif.engine.data.mongodb.drop=true

# Elasticsearch
netgrif.engine.data.elasticsearch.drop=true
netgrif.engine.data.elasticsearch.index.petriNet=${NETGRIF_ENGINE_DATA_DATABASE_NAME:nae}_dev_petrinet
netgrif.engine.data.elasticsearch.index.case=${NETGRIF_ENGINE_DATA_DATABASE_NAME:nae}_dev_case
netgrif.engine.data.elasticsearch.index.task=${NETGRIF_ENGINE_DATA_DATABASE_NAME:nae}_dev_task
netgrif.engine.data.elasticsearch.reindex=0 */10 * * * *

# Postal codes
netgrif.engine.postal-code.enable-import=false
netgrif.engine.postal-code.import-file-path=postal_codes_dev.csv

# Storage
netgrif.engine.storage.clean=true

# Security and Swagger
netgrif.engine.security.auth.admin-password=password
netgrif.engine.swagger.enabled=true
netgrif.engine.security.server-patterns=/api/auth/signup,/api/auth/token/verify,/api/auth/reset,/api/auth/recover,/v3/api-docs,/v3/api-docs/**,/swagger-ui.html,/swagger-ui/**,/api/public/**,/manage/health

# Actuator health checks
netgrif.engine.management.health.ldap.enabled=false
netgrif.engine.management.health.mail.enabled=false

# Dashboard
netgrif.engine.dashboard.enabled=true

# Logging levels
netgrif.engine.logging.level.org.springframework.data.elasticsearch.core=info
netgrif.engine.logging.level.com.netgrif.application.engine.elastic.service=info
netgrif.engine.logging.level.org.springframework.data.mongodb.core.MongoTemplate=info
netgrif.engine.logging.level.com.netgrif.application.engine.petrinet.domain.dataset.logic.action.FieldActionsRunner=debug
netgrif.engine.logging.level.com.netgrif.application.engine.petrinet.domain.dataset.logic.action.runner.RoleActionsRunner=debug
netgrif.engine.logging.level.com.netgrif.application.engine.admin.AdminConsoleRunner=debug
netgrif.engine.logging.level.com.netgrif.application.engine.petrinet.domain.dataset.logic.action.runner.CaseFieldsExpressionRunner=debug

#netgrif.engine.logging.level.root=debug
